define({
  "AddNewProduct": "Dodaj nowy produkt",
  "Administration": "Administracja",
  "Amount": "Kwota",
  "BudgetAppName": "Budżet",
  "Calendar": "Kalendarz",
  "Cancel": "Anuluj",
  "CollectionShouldHaveAtLeastOneElement": "Kolekcja powinna posiadać co najmniej jeden element",
  "Date": "Data",
  "Language": "Język",
  "LogIntoApplication": "Zaloguj się do aplikacji",
  "Logout": "Wyloguj się",
  "ModifyProduct": "Modyfikuj produkt",
  "Name": "Nazwa",
  "New": "Nowy",
  "NewExpense": "Nowy wydatek",
  "OK": "OK",
  "Password": "Hasło",
  "PleaseWait": "Proszę czekać...",
  "Product": "Produkt",
  "Products": "Produkty",
  "SignIn": "Zaloguj się",
  "ThisFieldIsRequired": "To pole jest wymagane",
  "UnexpectedError": "Wystąpił nieoczekiwany błąd",
  "Username": "Nazwa użytkownika",
  "UsernameAndPasswordDontMatch": "Nazwa użytkownika i hasło nie pasują",
  "Welcome": "Witaj {0}"
});