define({
  "root": {
    "AddNewProduct": "Add new product",
    "Administration": "Administration",
    "Amount": "Amount",
    "BudgetAppName": "Budget",
    "Calendar": "Calendar",
    "Cancel": "Cancel",
    "CollectionShouldHaveAtLeastOneElement": "Collection should have at least one element",
    "Date": "Date",
    "Language": "Language",
    "LogIntoApplication": "Log into application",
    "Logout": "Log out",
    "ModifyProduct": "Modify product",
    "Name": "Name",
    "New": "New",
    "NewExpense": "New expense",
    "OK": "OK",
    "Password": "Password",
    "PleaseWait": "Please wait...",
    "Product": "Product",
    "Products": "Products",
    "SignIn": "Sign in",
    "ThisFieldIsRequired": "This field is required",
    "UnexpectedError": "Unexpected error occured",
    "Username": "Username",
    "UsernameAndPasswordDontMatch": "Username and password don't match",
    "Welcome": "Welcome {0}"
  },
  "pl": true
});